// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250423200905_AddVocabularyModuleAndWords")]
    partial class AddVocabularyModuleAndWords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.Languages.LanguageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlagImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryImage = "/assets/main/UK-main.jpg",
                            Description = "Англійська мова відкриває доступ до кращих освітніх, кар'єрних та культурних можливостей у світі, а також допомагає спілкуватися з людьми з різних країн. Це універсальний інструмент для подорожей, саморозвитку та успіху в багатьох сферах життя.",
                            FlagImage = "/assets/main/UK-flag.jpg",
                            Name = "Англійська мова"
                        },
                        new
                        {
                            Id = 2,
                            CountryImage = "/assets/main/France-main.jpg",
                            Description = "Французька мова є однією з основних мов міжнародної дипломатії, культури та мистецтва, відкриваючи доступ до освіти та роботи у франкомовних країнах. Вона також корисна для подорожей і розширює можливості у спілкуванні по всьому світу.",
                            FlagImage = "/assets/main/France-flag.jpg",
                            Name = "Французька мова"
                        },
                        new
                        {
                            Id = 3,
                            CountryImage = "/assets/main/Germany-main.jpg",
                            Description = "Німецька мова відкриває доступ до якісної освіти, кар'єрних можливостей у Європі та культурної спадщини німецькомовних країн. Вона також корисна для подорожей і бізнесу, адже є однією з найпоширеніших мов у ЄС.",
                            FlagImage = "/assets/main/Germany-flag.jpg",
                            Name = "Німецька мова"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Languages.UserLanguage", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.HasKey("UserId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("DAL.Entities.Lessons.LessonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("DAL.Entities.Modules.ModuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("DAL.Entities.Modules.QuizModuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("QuizModuleEntity");
                });

            modelBuilder.Entity("DAL.Entities.Modules.ReadingModuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("ReadingModuleEntity");
                });

            modelBuilder.Entity("DAL.Entities.Modules.SpeakingModuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("SpeakingModuleEntity");
                });

            modelBuilder.Entity("DAL.Entities.Modules.TheoryModuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("TheoryModules", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.Modules.VocabularyModuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("VocabularyModules");
                });

            modelBuilder.Entity("DAL.Entities.Relations.UsersToLessons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UsersToLessons");
                });

            modelBuilder.Entity("DAL.Entities.Tasks.FillInTheBlankTaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReadingModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReadingModuleId");

                    b.ToTable("FillInTheBlankTaskEntity");
                });

            modelBuilder.Entity("DAL.Entities.Tasks.QuizQuestionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectOptionIndex")
                        .HasColumnType("int");

                    b.Property<string>("Option1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizModuleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizModuleId");

                    b.ToTable("QuizQuestionEntity");
                });

            modelBuilder.Entity("DAL.Entities.Tasks.SpeakingPhraseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeakingModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SpeakingModuleId");

                    b.ToTable("SpeakingPhraseEntity");
                });

            modelBuilder.Entity("DAL.Entities.Tasks.TaskLangEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("TaskLangs");
                });

            modelBuilder.Entity("DAL.Entities.Tasks.WordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Transcription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VocabularyModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyModuleId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("DAL.Entities.Users.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DAL.Entities.Languages.LanguageEntity", b =>
                {
                    b.HasOne("DAL.Entities.Users.UserEntity", null)
                        .WithMany("Languages")
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("DAL.Entities.Languages.UserLanguage", b =>
                {
                    b.HasOne("DAL.Entities.Languages.LanguageEntity", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Users.UserEntity", "User")
                        .WithMany("UserLanguages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.Lessons.LessonEntity", b =>
                {
                    b.HasOne("DAL.Entities.Languages.LanguageEntity", "Language")
                        .WithMany("Lessons")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DAL.Entities.Modules.ModuleEntity", b =>
                {
                    b.HasOne("DAL.Entities.Lessons.LessonEntity", "Lesson")
                        .WithMany("Modules")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DAL.Entities.Modules.QuizModuleEntity", b =>
                {
                    b.HasOne("DAL.Entities.Lessons.LessonEntity", "Lesson")
                        .WithOne("Quiz")
                        .HasForeignKey("DAL.Entities.Modules.QuizModuleEntity", "LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DAL.Entities.Modules.ReadingModuleEntity", b =>
                {
                    b.HasOne("DAL.Entities.Lessons.LessonEntity", "Lesson")
                        .WithOne("Reading")
                        .HasForeignKey("DAL.Entities.Modules.ReadingModuleEntity", "LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DAL.Entities.Modules.SpeakingModuleEntity", b =>
                {
                    b.HasOne("DAL.Entities.Lessons.LessonEntity", "Lesson")
                        .WithOne("Speaking")
                        .HasForeignKey("DAL.Entities.Modules.SpeakingModuleEntity", "LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DAL.Entities.Modules.TheoryModuleEntity", b =>
                {
                    b.HasOne("DAL.Entities.Lessons.LessonEntity", "Lesson")
                        .WithOne("Theory")
                        .HasForeignKey("DAL.Entities.Modules.TheoryModuleEntity", "LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DAL.Entities.Modules.VocabularyModuleEntity", b =>
                {
                    b.HasOne("DAL.Entities.Lessons.LessonEntity", "Lesson")
                        .WithOne("Vocabulary")
                        .HasForeignKey("DAL.Entities.Modules.VocabularyModuleEntity", "LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DAL.Entities.Relations.UsersToLessons", b =>
                {
                    b.HasOne("DAL.Entities.Lessons.LessonEntity", "Lesson")
                        .WithMany("UsersToLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Users.UserEntity", "User")
                        .WithOne("UsersToLessons")
                        .HasForeignKey("DAL.Entities.Relations.UsersToLessons", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.Tasks.FillInTheBlankTaskEntity", b =>
                {
                    b.HasOne("DAL.Entities.Modules.ReadingModuleEntity", "ReadingModule")
                        .WithMany("Tasks")
                        .HasForeignKey("ReadingModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadingModule");
                });

            modelBuilder.Entity("DAL.Entities.Tasks.QuizQuestionEntity", b =>
                {
                    b.HasOne("DAL.Entities.Modules.QuizModuleEntity", "QuizModule")
                        .WithMany("Questions")
                        .HasForeignKey("QuizModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizModule");
                });

            modelBuilder.Entity("DAL.Entities.Tasks.SpeakingPhraseEntity", b =>
                {
                    b.HasOne("DAL.Entities.Modules.SpeakingModuleEntity", "SpeakingModule")
                        .WithMany("Phrases")
                        .HasForeignKey("SpeakingModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpeakingModule");
                });

            modelBuilder.Entity("DAL.Entities.Tasks.TaskLangEntity", b =>
                {
                    b.HasOne("DAL.Entities.Modules.ModuleEntity", "Module")
                        .WithMany("Tasks")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("DAL.Entities.Tasks.WordEntity", b =>
                {
                    b.HasOne("DAL.Entities.Modules.VocabularyModuleEntity", "VocabularyModule")
                        .WithMany("Words")
                        .HasForeignKey("VocabularyModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabularyModule");
                });

            modelBuilder.Entity("DAL.Entities.Languages.LanguageEntity", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("DAL.Entities.Lessons.LessonEntity", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("Quiz")
                        .IsRequired();

                    b.Navigation("Reading")
                        .IsRequired();

                    b.Navigation("Speaking")
                        .IsRequired();

                    b.Navigation("Theory")
                        .IsRequired();

                    b.Navigation("UsersToLessons");

                    b.Navigation("Vocabulary")
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Entities.Modules.ModuleEntity", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DAL.Entities.Modules.QuizModuleEntity", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("DAL.Entities.Modules.ReadingModuleEntity", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DAL.Entities.Modules.SpeakingModuleEntity", b =>
                {
                    b.Navigation("Phrases");
                });

            modelBuilder.Entity("DAL.Entities.Modules.VocabularyModuleEntity", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("DAL.Entities.Users.UserEntity", b =>
                {
                    b.Navigation("Languages");

                    b.Navigation("UserLanguages");

                    b.Navigation("UsersToLessons")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
